name: k8s.gcr.io镜像同步
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_SYNCER_VERSION: v1.3.1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: 检查
      uses: actions/checkout@v2

    - name: 安装阿里镜像同步工具
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
    - name: 初始化config.yaml配置文件
      run: |
        sed -i "s#USERNAME#${DOCKERHUB_USERNAME}#g" config.yaml
        sed -i "s#PASSWORD#${DOCKERHUB_PASSWORD}#g" config.yaml
        
    - name: 同步镜像到docker-hub
      run: |
        ./image-syncer --proc=20 --config=config.yaml --retries=1
