name: Demo Push

on:   
  push:
    branches:
      - main
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

jobs:

  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    strategy:
      fail-fast: false
      matrix:
        include:  
          - podname: k8s.gcr.io/pause
            version: 3.5
            
    steps:
      - name: Checkout ghcr.io 
        uses: actions/checkout@v2

      - name: 构建镜像
        run: docker build . --file pause/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}:${{matrix.version}}

      - name: 登录ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}:${{matrix.version}}
        
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}:${{matrix.version}}