name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Checkout
      uses: actions/checkout@v2

    - name: cache
      uses: actions/upload-artifact@v2
      with:
        name: test.tar.gz
        path: image/test.tar.gz
        if-no-files-found: error
