name: Demo Push

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    strategy:
      fail-fast: false
      matrix:
        include:  
          - podname: pause
            version: [3.5,3.6]
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file pause/Dockerfile --tag ${{matrix.podname}}:${{matrix.version}}

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ${{matrix.podname}}:${{matrix.version}} ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}-${{matrix.version}}:${{matrix.version}}
          docker push ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}-${{matrix.version}}:${{matrix.version}}