name: 镜像推送

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  # Use docker.io for Docker Hub if empty
  hub_registry: docker.io
  # github.repository as <account>/<repo>
  hub_name: xyz349925756


jobs:
  build:

    runs-on: ubuntu-latest
    name: 编译 "${{matrix.podname}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - podname: k8s.gcr.io/coredns/coredns
            pod-name: coredns
            version: v1.8.6
          - podname: k8s.gcr.io/ingress-nginx/controller
            pod-name: ingress-nginx-controller
            version: v1.0.5
          - podname: k8s.gcr.io/ingress-nginx/kube-webhook-certgen
            pod-name: ingress-nginx-kube-webhook-certgen
            version: v1.1.1
          - podname: k8s.gcr.io/metrics-server/metrics-server
            pod-name: metrics-server
            version: v0.5.2      
          - podname: pause
            pod-name: pause
            version: 3.5
            
    steps:
      - name: 准备...
        uses: actions/checkout@v2

      - name: 登录 "${{ env.hub_registry }}"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.hub_registry }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "构建及上传"
        uses: docker/build-push-action@v2
        run:
          docker build . --file pause/Dockerfile --tag ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker push ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker build . --file coredns/Dockerfile --tag ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker push ${{hub_name}}/${{matrix.podname}}:${{matrix.version}} 
          docker build . --file metrics-server/Dockerfile --tag ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker push ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker build . --file ingress-nginx-controller/Dockerfile --tag ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker push ${{hub_name}}/${{matrix.podname}}:${{matrix.version}} 
          docker build . --file ingress-nginx-kube-webhook-certgen/Dockerfile --tag ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}
          docker push ${{hub_name}}/${{matrix.podname}}:${{matrix.version}}  
